name: Manual Workflow

on:
  workflow_dispatch:  # Enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use TAIS_JWT Secret
        env:
          TAIS_JWT: ${{ secrets.TAIS_JWT }}  # Maps the secret to an env variable
        run: |
          echo "TAIS_JWT is set to $TAIS_JWT"
          # Add your script or command here that uses TAIS_JWT
